# Dockerfile.frontend

# Usando uma imagem Python base
FROM python:3.12-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto para o container
COPY . /app

# Instala as dependências necessárias
RUN pip install --no-cache-dir PyQt5 Faker requests

# Expor a porta que o frontend irá usar (opcional)
EXPOSE 3000

# Comando para iniciar o frontend
CMD ["python", "frontend.py"]