version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile.backend
    container_name: backend
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.10

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile.frontend
    container_name: frontend
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.11

  banco:
    image: postgres:13
    container_name: banco
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-defaultpassword}"
      POSTGRES_DB: "${POSTGRES_DB:-db_passagem}"
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.12
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.13
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  venda_passagem:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24