version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile.backend
    container_name: backend
    privileged: true
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.10
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do backend

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile.frontend
    container_name: frontend
    privileged: true
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.11
    ports:
      - "3000:3000"  # Mapeando a porta 3000 do frontend

  banco:
    image: postgres:13
    container_name: banco
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-defaultpassword}"
      POSTGRES_DB: "${POSTGRES_DB:-db_passagem}"
    privileged: true
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.12
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.13
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  venda_passagem:
    name: venda_passagem  # Define o nome fixo da rede
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24