version: '3.8'

services:
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile.backend
    container_name: backend
    privileged: true
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.10
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile.frontend
    container_name: frontend
    privileged: true
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.11
    ports:
      - "3000:3000"

  banco:
    build:
      context: ./DB
      dockerfile: Dockerfile.banco
    container_name: banco
    image: postgres:13
    privileged: true
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.12
    ports:
      - "5432:5432"

  rabbitmq:
    build:
      context: ./RABITMQ
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    networks:
      venda_passagem:
        ipv4_address: 192.168.1.13
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  venda_passagem:
    name: venda_passagem
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24