FROM rabbitmq:3-management

# Definindo o usuário e a senha padrão do RabbitMQ
ENV RABBITMQ_DEFAULT_USER=usuario \
    RABBITMQ_DEFAULT_PASS=12345

# Instala o Python e o Pika
RUN apt-get update && apt-get install -y python3 python3-pip && \
    pip3 install pika && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copiando o arquivo rabbitmq.py para dentro do container
COPY rabbitmq.py /app/rabbitmq.py

# Expondo as portas do RabbitMQ
EXPOSE 5672 15672